### PR TITLE
Escape square brackets, braces and at characters in text nodes (fixes #4)

### LINKED ISSUE #4: Missing escaping of brackets
`md2mld` (version 0.3.0 from OPAM) does not seem to escape brackets from Markdown. If I take the file:

```
Here is some text [...] and then some more.

Here is a bracket: [

Here is a closing bracket: ]
```

I get an identical `.mld` file. If I then give this file to odoc, it complains and produces an HTML like the following:

image

where the brackets have been interpreted as code. It should look like the following in Markdown:

image

### PR DESCRIPTION
**Pull request by dmbaturin**
As @niols pointes out in #4, 

>special characters (’{’, ’}’, ’[’, ’]’ and ’@’) must be escaped by a ’\’.

None of these characters have any special meaning by themselves in Markdown. Square brackets only have a special meaning in the `[<link text>](<link address>)` syntax, and in that case Omd returns an `Omd.Link` node so they don't appear in the text. The only case when they can appear and need escaping is `Omd.Text`.

One peculiarity of current Omd versions is that insignificant square brackets still force it emit a text node, so any text with anything in square brackets will produce three nodes instead of one. It doesn't change escaping logic, however. 

```ocaml
utop # Omd.of_string "[text in brackets]" ;;
- : Omd.doc =
[Omd.Paragraph ([],
  Omd.Concat ([],
   [Omd.Text ([], "["); Omd.Text ([], "text in brackets"); Omd.Text ([], "]")]))]
```
With my patch it seems to behave as expected:

```
$ echo 'Text with [square brackets], {braces}, and @-characters' | ./_build/default/src/md2mld.exe
Text with \[square brackets\], \{braces\}, and \@-characters
```

(Stdin reading support is from #8)

### CODE REVIEW

**Comment by mseri** [comment]
Thanks! As the other I’ll wait for ci to finish. I will make a new release in the next few days

**Comment by dmbaturin** [comment]
> Thanks! As the other I’ll wait for ci to finish. I will make a new release in the next few days

Tests fail because of ocp-indent errors at the `dune build @fmt` stage, and the problem is that it fails on _your_ original code, so that code needs to be reformatted before the CI run can succeed.

How should we go about it? Shall I  make a separate PR for formatting fixes and rebase these two PRs to that new branch?

**Comment by mseri** [comment]
I should probably fix a ocaml format version. Let’s not worry about that

**Comment by mseri** [comment]
I’ll fix it manually before release tomorrow or on Tuesday

**Comment by dmbaturin** [comment]
@mseri I also wanted to add a `--version` option before the next release. I'm not sure what would be your preferred approach to storing the option, though — whether you are fine with a hardcoded constant or you prefer cppo or similar.

**Comment by mseri** [comment]
We can use dune subst mechanism I think

**Pull request merged**
